export enum InfoType {
    COTISATION = 'COTISATION',
    USER_DELETE = 'USER_DELETE',
    USER_INVITE = 'USER_INVITE',
    USER_CREATE = 'USER_CREATE',
    USER_FIRST_CONNECTION = 'USER_FIRST_CONNECTION',
    USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
    COTISATION_PAYMENT = 'COTISATION_PAYMENT',
    CLUB_CREATE = 'CLUB_CREATE',
    CLUB_DELETE = 'CLUB_DELETE',
    CLUB_UPDATE = 'CLUB_UPDATE',

}