export enum MessageType {

    FIRST_CONNECTION = 'FIRST_CONNECTION',
    A2F_CODE = 'A2F_CODE',
    NEW_EVENT_ALERT = 'NEW_EVENT_ALERT',
    CANCELED_EVENT_ALERT = 'CANCELED_EVENT_ALERT',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    NEWSLETTER = 'NEWSLETTER',
    CREATE_COTISATION = "CREATE_COTISATION",
    REMINDER_COTISATION = "REMINDER_COTISATION",
    DELETE_COTISATION = "DELETE_COTISATION",
    CARD_CREATED = "CARD_CREATED",
    PAYMENT_COTISATION = "PAYMENT_COTISATION",
    USER_REACTIVATE = "USER_REACTIVATE",
    USER_DEACTIVATE = "USER_DEACTIVATE",
    LOST_PASSWORD = "LOST_PASSWORD",

}