export enum MessageType {

    FIRST_CONNECTION = 'FIRST_CONNECTION',
    A2F_CODE = 'A2F_CODE',
    NEW_EVENT_ALERT = 'NEW_EVENT_ALERT',
    CANCELED_EVENT_ALERT = 'CANCELED_EVENT_ALERT',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    NEWSLETTER = 'NEWSLETTER',
}