export enum Role {
    ADMIN = 'ADMIN',
    ADMIN_CLUB = 'ADMIN_CLUB',
    ADMIN_FORMATIONCENTER = 'ADMIN_FORMATIONCENTER',
    CLUB = 'CLUB',
    FORMATIONCENTER = 'FORMATIONCENTER',
    PLAYER = 'PLAYER'
}