import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1715939982730 implements MigrationInterface {
    name = 'Init1715939982730'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NOT NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Role\` varchar(255) NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planning\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titre\` varchar(255) NOT NULL, \`description\` text NULL, \`date_debut\` datetime NOT NULL, \`date_fin\` datetime NOT NULL, \`lieu\` varchar(255) NULL, \`type_activite\` varchar(255) NULL, \`recurrence\` varchar(255) NULL, \`statut\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Name\` varchar(255) NOT NULL, \`Adress\` varchar(255) NOT NULL, \`Id_Image\` int NOT NULL, \`creation_date\` datetime NOT NULL, \`imageId\` int NULL, UNIQUE INDEX \`REL_666bf4bf29482dfe470be67bb6\` (\`imageId\`), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`location\` varchar(255) NOT NULL, \`type\` varchar(255) NULL, \`recurrence\` varchar(255) NULL, \`capacity\` int NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`formation_center\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Name\` varchar(255) NOT NULL, \`Adress\` varchar(255) NOT NULL, \`Email\` varchar(255) NOT NULL, \`Creation_Date\` datetime NOT NULL, \`Id_Image\` int NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sport\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Name\` varchar(255) NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`FirstName\` varchar(255) NOT NULL, \`Lastname\` varchar(255) NOT NULL, \`Height\` int NOT NULL, \`Weight\` int NOT NULL, \`BirthDate\` date NULL, \`stats\` json NULL, \`formationCenterId\` int NULL, \`sportId\` int NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`image\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`url\` varchar(255) NOT NULL, \`playersId\` int NULL, \`userId\` int NULL, \`clubId\` int NULL, UNIQUE INDEX \`REL_dc40417dfa0c7fbd70b8eb880c\` (\`userId\`), UNIQUE INDEX \`REL_3f8f5a888e3133dcb47e315b51\` (\`clubId\`), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`firstname\` varchar(255) NOT NULL, \`lastname\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`birth_date\` datetime NOT NULL, \`date_creation\` datetime NOT NULL, \`address\` varchar(255) NOT NULL, \`matricule\` int NOT NULL, \`password\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), UNIQUE INDEX \`IDX_259473ab221f66ce5b7842195f\` (\`matricule\`), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vote\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Description\` varchar(255) NOT NULL, \`Timeat\` datetime NOT NULL, \`Creation_Date\` datetime NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`new_letter\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Message\` varchar(255) NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`dons\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Date\` datetime NOT NULL, \`Amount\` int NOT NULL, \`Transaction_Id\` int NOT NULL, \`Transaction_Status\` varchar(255) NOT NULL, \`Transaction_Type\` varchar(255) NOT NULL, \`Payment_Method\` varchar(255) NOT NULL, \`Creation_Date\` datetime NOT NULL, \`Receipt_Number\` int NOT NULL, \`Payer_Id\` int NOT NULL, \`Comments\` varchar(255) NOT NULL, \`Ip_Adresse\` varchar(255) NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`documents\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Type\` varchar(255) NOT NULL, \`Path\` varchar(255) NOT NULL, \`Name\` varchar(255) NOT NULL, \`User_Id\` int NOT NULL, \`Id_Image\` int NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles_user_user\` (\`rolesId\` int NOT NULL, \`userId\` int NOT NULL, INDEX \`IDX_894317781db6f714b16a82c5dc\` (\`rolesId\`), INDEX \`IDX_2f5f1c036feb52c9570583bc01\` (\`userId\`), PRIMARY KEY (\`rolesId\`, \`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planning_users_user\` (\`planningId\` int NOT NULL, \`userId\` int NOT NULL, INDEX \`IDX_75fac81f985d0c9dfc2ad03f67\` (\`planningId\`), INDEX \`IDX_1bd384becb069f63abdfd50f46\` (\`userId\`), PRIMARY KEY (\`planningId\`, \`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_sports_sport\` (\`clubId\` int NOT NULL, \`sportId\` int NOT NULL, INDEX \`IDX_8ba909ebfe6332ecbbd1ee43dd\` (\`clubId\`), INDEX \`IDX_33a6c9a4a1445af38ee0b5adf2\` (\`sportId\`), PRIMARY KEY (\`clubId\`, \`sportId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events_participants_user\` (\`eventsId\` int NOT NULL, \`userId\` int NOT NULL, INDEX \`IDX_583e1ad566215b2d990a8534a5\` (\`eventsId\`), INDEX \`IDX_b8c1e88ae770fc8b1a6216c3b8\` (\`userId\`), PRIMARY KEY (\`eventsId\`, \`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events_clubs_club\` (\`eventsId\` int NOT NULL, \`clubId\` int NOT NULL, INDEX \`IDX_2039a68573a6dd7fac82c0df1c\` (\`eventsId\`), INDEX \`IDX_4ddf71477a8d18d9d59c24fa33\` (\`clubId\`), PRIMARY KEY (\`eventsId\`, \`clubId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events_training_centers_formation_center\` (\`eventsId\` int NOT NULL, \`formationCenterId\` int NOT NULL, INDEX \`IDX_5a9a7c3862e098ee844544a60b\` (\`eventsId\`), INDEX \`IDX_33c1cd836f924934fadfa880d6\` (\`formationCenterId\`), PRIMARY KEY (\`eventsId\`, \`formationCenterId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`formation_center_sports_sport\` (\`formationCenterId\` int NOT NULL, \`sportId\` int NOT NULL, INDEX \`IDX_dcf11396d8b004d547d397c53b\` (\`formationCenterId\`), INDEX \`IDX_4223996f06f11a57c0700be7e8\` (\`sportId\`), PRIMARY KEY (\`formationCenterId\`, \`sportId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles_roles\` (\`userId\` int NOT NULL, \`rolesId\` int NOT NULL, INDEX \`IDX_0d0cc409255467b0ac4fe6b169\` (\`userId\`), INDEX \`IDX_7521d8491e7c51f885e9f861e0\` (\`rolesId\`), PRIMARY KEY (\`userId\`, \`rolesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vote_users_user\` (\`voteId\` int NOT NULL, \`userId\` int NOT NULL, INDEX \`IDX_87635a654750c72ba9b2de9be9\` (\`voteId\`), INDEX \`IDX_8bf140af0b90a4bc9f9352669c\` (\`userId\`), PRIMARY KEY (\`voteId\`, \`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`token\` ADD CONSTRAINT \`FK_94f168faad896c0786646fa3d4a\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club\` ADD CONSTRAINT \`FK_666bf4bf29482dfe470be67bb6e\` FOREIGN KEY (\`imageId\`) REFERENCES \`image\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player\` ADD CONSTRAINT \`FK_b0f77cf303ce14bc2a97c3f1943\` FOREIGN KEY (\`formationCenterId\`) REFERENCES \`formation_center\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player\` ADD CONSTRAINT \`FK_6630f1469adbbd13fa924067eee\` FOREIGN KEY (\`sportId\`) REFERENCES \`sport\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image\` ADD CONSTRAINT \`FK_118d4f5a662968a8fb17dc37990\` FOREIGN KEY (\`playersId\`) REFERENCES \`player\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image\` ADD CONSTRAINT \`FK_dc40417dfa0c7fbd70b8eb880cc\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image\` ADD CONSTRAINT \`FK_3f8f5a888e3133dcb47e315b514\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_user_user\` ADD CONSTRAINT \`FK_894317781db6f714b16a82c5dcb\` FOREIGN KEY (\`rolesId\`) REFERENCES \`roles\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`roles_user_user\` ADD CONSTRAINT \`FK_2f5f1c036feb52c9570583bc01b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`planning_users_user\` ADD CONSTRAINT \`FK_75fac81f985d0c9dfc2ad03f672\` FOREIGN KEY (\`planningId\`) REFERENCES \`planning\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planning_users_user\` ADD CONSTRAINT \`FK_1bd384becb069f63abdfd50f466\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_sports_sport\` ADD CONSTRAINT \`FK_8ba909ebfe6332ecbbd1ee43dd4\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`club_sports_sport\` ADD CONSTRAINT \`FK_33a6c9a4a1445af38ee0b5adf2c\` FOREIGN KEY (\`sportId\`) REFERENCES \`sport\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`events_participants_user\` ADD CONSTRAINT \`FK_583e1ad566215b2d990a8534a52\` FOREIGN KEY (\`eventsId\`) REFERENCES \`events\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`events_participants_user\` ADD CONSTRAINT \`FK_b8c1e88ae770fc8b1a6216c3b81\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`events_clubs_club\` ADD CONSTRAINT \`FK_2039a68573a6dd7fac82c0df1c4\` FOREIGN KEY (\`eventsId\`) REFERENCES \`events\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`events_clubs_club\` ADD CONSTRAINT \`FK_4ddf71477a8d18d9d59c24fa333\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`events_training_centers_formation_center\` ADD CONSTRAINT \`FK_5a9a7c3862e098ee844544a60b4\` FOREIGN KEY (\`eventsId\`) REFERENCES \`events\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`events_training_centers_formation_center\` ADD CONSTRAINT \`FK_33c1cd836f924934fadfa880d6c\` FOREIGN KEY (\`formationCenterId\`) REFERENCES \`formation_center\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`formation_center_sports_sport\` ADD CONSTRAINT \`FK_dcf11396d8b004d547d397c53b6\` FOREIGN KEY (\`formationCenterId\`) REFERENCES \`formation_center\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`formation_center_sports_sport\` ADD CONSTRAINT \`FK_4223996f06f11a57c0700be7e8d\` FOREIGN KEY (\`sportId\`) REFERENCES \`sport\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles_roles\` ADD CONSTRAINT \`FK_0d0cc409255467b0ac4fe6b1693\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles_roles\` ADD CONSTRAINT \`FK_7521d8491e7c51f885e9f861e02\` FOREIGN KEY (\`rolesId\`) REFERENCES \`roles\`(\`Id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vote_users_user\` ADD CONSTRAINT \`FK_87635a654750c72ba9b2de9be91\` FOREIGN KEY (\`voteId\`) REFERENCES \`vote\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vote_users_user\` ADD CONSTRAINT \`FK_8bf140af0b90a4bc9f9352669cf\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`Id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`vote_users_user\` DROP FOREIGN KEY \`FK_8bf140af0b90a4bc9f9352669cf\``);
        await queryRunner.query(`ALTER TABLE \`vote_users_user\` DROP FOREIGN KEY \`FK_87635a654750c72ba9b2de9be91\``);
        await queryRunner.query(`ALTER TABLE \`user_roles_roles\` DROP FOREIGN KEY \`FK_7521d8491e7c51f885e9f861e02\``);
        await queryRunner.query(`ALTER TABLE \`user_roles_roles\` DROP FOREIGN KEY \`FK_0d0cc409255467b0ac4fe6b1693\``);
        await queryRunner.query(`ALTER TABLE \`formation_center_sports_sport\` DROP FOREIGN KEY \`FK_4223996f06f11a57c0700be7e8d\``);
        await queryRunner.query(`ALTER TABLE \`formation_center_sports_sport\` DROP FOREIGN KEY \`FK_dcf11396d8b004d547d397c53b6\``);
        await queryRunner.query(`ALTER TABLE \`events_training_centers_formation_center\` DROP FOREIGN KEY \`FK_33c1cd836f924934fadfa880d6c\``);
        await queryRunner.query(`ALTER TABLE \`events_training_centers_formation_center\` DROP FOREIGN KEY \`FK_5a9a7c3862e098ee844544a60b4\``);
        await queryRunner.query(`ALTER TABLE \`events_clubs_club\` DROP FOREIGN KEY \`FK_4ddf71477a8d18d9d59c24fa333\``);
        await queryRunner.query(`ALTER TABLE \`events_clubs_club\` DROP FOREIGN KEY \`FK_2039a68573a6dd7fac82c0df1c4\``);
        await queryRunner.query(`ALTER TABLE \`events_participants_user\` DROP FOREIGN KEY \`FK_b8c1e88ae770fc8b1a6216c3b81\``);
        await queryRunner.query(`ALTER TABLE \`events_participants_user\` DROP FOREIGN KEY \`FK_583e1ad566215b2d990a8534a52\``);
        await queryRunner.query(`ALTER TABLE \`club_sports_sport\` DROP FOREIGN KEY \`FK_33a6c9a4a1445af38ee0b5adf2c\``);
        await queryRunner.query(`ALTER TABLE \`club_sports_sport\` DROP FOREIGN KEY \`FK_8ba909ebfe6332ecbbd1ee43dd4\``);
        await queryRunner.query(`ALTER TABLE \`planning_users_user\` DROP FOREIGN KEY \`FK_1bd384becb069f63abdfd50f466\``);
        await queryRunner.query(`ALTER TABLE \`planning_users_user\` DROP FOREIGN KEY \`FK_75fac81f985d0c9dfc2ad03f672\``);
        await queryRunner.query(`ALTER TABLE \`roles_user_user\` DROP FOREIGN KEY \`FK_2f5f1c036feb52c9570583bc01b\``);
        await queryRunner.query(`ALTER TABLE \`roles_user_user\` DROP FOREIGN KEY \`FK_894317781db6f714b16a82c5dcb\``);
        await queryRunner.query(`ALTER TABLE \`image\` DROP FOREIGN KEY \`FK_3f8f5a888e3133dcb47e315b514\``);
        await queryRunner.query(`ALTER TABLE \`image\` DROP FOREIGN KEY \`FK_dc40417dfa0c7fbd70b8eb880cc\``);
        await queryRunner.query(`ALTER TABLE \`image\` DROP FOREIGN KEY \`FK_118d4f5a662968a8fb17dc37990\``);
        await queryRunner.query(`ALTER TABLE \`player\` DROP FOREIGN KEY \`FK_6630f1469adbbd13fa924067eee\``);
        await queryRunner.query(`ALTER TABLE \`player\` DROP FOREIGN KEY \`FK_b0f77cf303ce14bc2a97c3f1943\``);
        await queryRunner.query(`ALTER TABLE \`club\` DROP FOREIGN KEY \`FK_666bf4bf29482dfe470be67bb6e\``);
        await queryRunner.query(`ALTER TABLE \`token\` DROP FOREIGN KEY \`FK_94f168faad896c0786646fa3d4a\``);
        await queryRunner.query(`DROP INDEX \`IDX_8bf140af0b90a4bc9f9352669c\` ON \`vote_users_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_87635a654750c72ba9b2de9be9\` ON \`vote_users_user\``);
        await queryRunner.query(`DROP TABLE \`vote_users_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_7521d8491e7c51f885e9f861e0\` ON \`user_roles_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_0d0cc409255467b0ac4fe6b169\` ON \`user_roles_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_4223996f06f11a57c0700be7e8\` ON \`formation_center_sports_sport\``);
        await queryRunner.query(`DROP INDEX \`IDX_dcf11396d8b004d547d397c53b\` ON \`formation_center_sports_sport\``);
        await queryRunner.query(`DROP TABLE \`formation_center_sports_sport\``);
        await queryRunner.query(`DROP INDEX \`IDX_33c1cd836f924934fadfa880d6\` ON \`events_training_centers_formation_center\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a9a7c3862e098ee844544a60b\` ON \`events_training_centers_formation_center\``);
        await queryRunner.query(`DROP TABLE \`events_training_centers_formation_center\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ddf71477a8d18d9d59c24fa33\` ON \`events_clubs_club\``);
        await queryRunner.query(`DROP INDEX \`IDX_2039a68573a6dd7fac82c0df1c\` ON \`events_clubs_club\``);
        await queryRunner.query(`DROP TABLE \`events_clubs_club\``);
        await queryRunner.query(`DROP INDEX \`IDX_b8c1e88ae770fc8b1a6216c3b8\` ON \`events_participants_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_583e1ad566215b2d990a8534a5\` ON \`events_participants_user\``);
        await queryRunner.query(`DROP TABLE \`events_participants_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_33a6c9a4a1445af38ee0b5adf2\` ON \`club_sports_sport\``);
        await queryRunner.query(`DROP INDEX \`IDX_8ba909ebfe6332ecbbd1ee43dd\` ON \`club_sports_sport\``);
        await queryRunner.query(`DROP TABLE \`club_sports_sport\``);
        await queryRunner.query(`DROP INDEX \`IDX_1bd384becb069f63abdfd50f46\` ON \`planning_users_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_75fac81f985d0c9dfc2ad03f67\` ON \`planning_users_user\``);
        await queryRunner.query(`DROP TABLE \`planning_users_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f5f1c036feb52c9570583bc01\` ON \`roles_user_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_894317781db6f714b16a82c5dc\` ON \`roles_user_user\``);
        await queryRunner.query(`DROP TABLE \`roles_user_user\``);
        await queryRunner.query(`DROP TABLE \`documents\``);
        await queryRunner.query(`DROP TABLE \`dons\``);
        await queryRunner.query(`DROP TABLE \`new_letter\``);
        await queryRunner.query(`DROP TABLE \`vote\``);
        await queryRunner.query(`DROP INDEX \`IDX_259473ab221f66ce5b7842195f\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`REL_3f8f5a888e3133dcb47e315b51\` ON \`image\``);
        await queryRunner.query(`DROP INDEX \`REL_dc40417dfa0c7fbd70b8eb880c\` ON \`image\``);
        await queryRunner.query(`DROP TABLE \`image\``);
        await queryRunner.query(`DROP TABLE \`player\``);
        await queryRunner.query(`DROP TABLE \`sport\``);
        await queryRunner.query(`DROP TABLE \`formation_center\``);
        await queryRunner.query(`DROP TABLE \`events\``);
        await queryRunner.query(`DROP INDEX \`REL_666bf4bf29482dfe470be67bb6\` ON \`club\``);
        await queryRunner.query(`DROP TABLE \`club\``);
        await queryRunner.query(`DROP TABLE \`planning\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`token\``);
    }

}
